### PR TITLE
Fix error of Buzzer.h not found

### LINKED ISSUE #14: buzzer.h not found (A10M)
I'm trying to build latest commit from this repo for the A10M on Arduino IDE 1.8.5.
I get the following error:
```
sketch/stepper.cpp:57:20: fatal error: Buzzer.h: No such file or directory
 #include "Buzzer.h"
```

Please advise on how to solve this problem.

### PR DESCRIPTION
**Pull request by fishcu**
Fixes #14. Only tested for A10M folder; But other folders should work exactly the same.

### CODE REVIEW

**Comment by Geeetech3D** [comment]
Fix error of Buzzer.h not found.

**Comment by Geeetech3D** [comment]
Fix error of Buzzer.h not found..

**Comment by Geeetech3D** [comment]
Fix error of Buzzer.h not found

**Comment by Geeetech3D** [comment]
Fix error of Buzzer.h not found

**Comment by Geeetech3D** [comment]
..

**Comment by Geeetech3D** [comment]
..

**Comment by Geeetech3D** [comment]
,,

**Comment by fishcu** [comment]
Thanks for fixing the issue! :+1: You can also merge the pull request automatically, then you won't have to apply the change manually! :)

**Pull request closed without merging**
